apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-service
  namespace: ecommerce
spec:
  scaleTargetRef:
    name: payment-service
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 60
  pollingInterval: 15
  triggers:
    - type: memory
      metricType: AverageValue
      metadata:
        value: "409Mi"
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: http_server_requests_seconds_count
        query: |
          sum(rate(http_server_requests_seconds_count{namespace="ecommerce",pod=~"payment-service-.*"}[1m])) * 60
        threshold: "600"
