apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: ecommerce-lab
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: change-me-root-password
  MARIADB_APP_USERNAME: cloud
  MARIADB_APP_PASSWORD: change-me-db-password
