apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ecommerce
spec:
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
  namespace: ecommerce
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
