apiVersion: v1
kind: Service
metadata:
  name: frontend-stable
  namespace: ecommerce
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: v1
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  namespace: ecommerce
spec:
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: v2
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
