# MongoDB 이미지 설정 (bitnami → bitnamilegacy 변경)
image:
  registry: docker.io
  repository: bitnamilegacy/mongodb
  tag: 8.0.9-debian-12-r2
  pullPolicy: IfNotPresent

# MongoDB 아키텍처 설정
# standalone | replicaset
architecture: standalone
replicaCount: 1

# 인증 설정
auth:
  enabled: true
  rootUser: root
  rootPassword: "Skala25a!23$"
  usernames: ["skala"]
  passwords: ["Skala25a!23$"]
  databases: ["cloud"]

# 스토리지 설정
persistence:
  enabled: true
  storageClass: "gp2"
  accessModes:
    - ReadWriteOnce
  size: 20Gi

# 서비스 설정
service:
  type: ClusterIP
  ports:
    mongodb: 27017

# 아비터 비활성화 (Active-Standby 구성을 위해)
arbiter:
  enabled: false

# 리소스 설정
resourcesPreset: "small"

# 네트워크 정책
networkPolicy:
  enabled: true
  allowExternal: true  # 외부 접속 허용
  allowExternalEgress: true

# Pod 보안 설정
podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
