apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-lab-config
  namespace: ecommerce
data:
  APP_HOST: skala3-cloud1-team4.cloud.skala-ai.com
  INGRESS_CLASS_NAME: nginx
  SPRING_PROFILES_ACTIVE: mariadb
  JAVA_OPTS: "-XX:InitialRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/./urandom"
  MARIADB_HOST: mariadb
  MARIADB_PORT: "3306"
  USER_SERVICE_DB: user_service_db
  PRODUCT_SERVICE_DB: product_service_db
  ORDER_SERVICE_DB: order_service_db
  PAYMENT_SERVICE_DB: payment_service_db
  USER_SERVICE_BASE_URL: http://user-service:8080
  PRODUCT_SERVICE_BASE_URL: http://product-service:8080
  ORDER_SERVICE_BASE_URL: http://order-service:8080
  PAYMENT_SERVICE_BASE_URL: http://payment-service:8080
