apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-lab-secret
  namespace: ecommerce-lab
type: Opaque
stringData:
  MARIADB_USERNAME: cloud
  MARIADB_PASSWORD: change-me-db-password
---
apiVersion: v1
kind: Secret
metadata:
  name: shopping-mall-tls
  namespace: ecommerce-lab
type: kubernetes.io/tls
stringData:
  tls.crt: REPLACE_WITH_TLS_CERTIFICATE
  tls.key: REPLACE_WITH_TLS_PRIVATE_KEY
