apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-lab-secret
  namespace: ecommerce
type: Opaque
stringData:
  MARIADB_USERNAME: cloud
  MARIADB_PASSWORD: change-me-db-password
  MARIADB_ROOT_PASSWORD: change-me-root-password
